name: Issues workflow
on:
  issues:
    types:
      - opened
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Echo details
        run: echo "${{github}}"
